
[Interface]
PrivateKey = 4MpR79CR0DQ6IlBTsdlVl2zhCy/gc/4GSfE5YnTMp0M=
Address = 10.8.0.2/24
DNS = 1.1.1.1,8.8.8.8

[Peer]
PublicKey = JQjMB7NT6HMNK+rwBMhofUEsWVXFsyT6x8U/XUrmki4=
PresharedKey = f3OIvwPZPat9sQMDvaN/h7e8tAyqCrSyDjkuAbPsdnw=
AllowedIPs = 0.0.0.0/1,128.0.0.0/1,192.168.0.0/16
PersistentKeepalive = 25
Endpoint = 192.168.0.49:51820